version: '3'

services:

  foswiki:
    image: timlegge/docker-foswiki:latest
    restart: always
    depends_on: 
      - solr
    networks:
      - frontend
      - backend
    ports:
      - "8765:80"
    volumes:
      - ./backup/:/backup/
      - ../volumes/wiki_backup/:/backup_data/
      - solr_logs:/opt/solr/server/logs:z
      - solr_configsets:/opt/solr/server/solr/configsets:z
      - solr_foswiki:/opt/solr/server/solr/solr_foswiki:z
      # - foswiki_www:/var/www/foswiki:z
      - ../volumes/wiki_data:/var/www/foswiki

  solr:
    image: solr:5
    restart: always
    networks:
      - backend
    volumes:
      - solr_logs:/opt/solr/server/logs:z
      - solr_configsets:/opt/solr/server/solr/configsets:z
      - solr_foswiki:/opt/solr/server/solr/solr_foswiki:z
      - foswiki_www:/var/www/foswiki:z
    environment:
      - GC_LOG_OPTS=''
      - SOLR_LOG_LEVEL='WARN'

volumes:
  foswiki_www:
  solr_configsets:
  solr_foswiki:
  solr_logs:

networks:
  frontend:
  backend:
    internal: true
