
name: foswiki

services:
  foswiki:
    # image: timlegge/docker-foswiki:latest
    build:
      context: './overlay/'
    restart: always
    hostname: foswiki.docker.local
    depends_on:
      - solr
    networks:
      proxy:
      authentik:
      backend:
    ports:
      - "127.0.0.1:8765:80"
    volumes:
      - ./backup/:/backup/
      - ./volumes/backup/:/backup_data/
      - ./volumes/data:/var/www/foswiki
      - solr_logs:/opt/solr/server/logs:z
      - solr_configsets:/opt/solr/server/solr/configsets:z
      - solr_foswiki:/opt/solr/server/solr/solr_foswiki:z
      # - foswiki_www:/var/www/foswiki
      - ./https/nginx.default.conf:/etc/nginx/http.d/default.conf
      - ./https/docker-foswiki.crt:/etc/nginx/docker-foswiki.crt
      - ./https/docker-foswiki.key:/etc/nginx/docker-foswiki.key
      
    environment:
      - HTTPS_CA_FILE=/etc/ssl/certs/ca-certificates.crt
      - HTTPS_CA_PATH=/etc/ssl/certs/
      # - PERL_LWP_VERIFY_HOSTNAME=0

  solr:
    image: solr:5
    restart: always
    networks:
      - backend
    volumes:
      - solr_logs:/opt/solr/server/logs:z
      - solr_configsets:/opt/solr/server/solr/configsets:z
      - solr_foswiki:/opt/solr/server/solr/solr_foswiki:z
      - ./volumes/data:/var/www/foswiki
    environment:
      - GC_LOG_OPTS=''
      - SOLR_LOG_LEVEL='WARN'

  # for automated backups
  backrest:
    # image: garethgeorge/backrest:latest
    # container_name: backrest-log
    image: mcculler/backrest-log
    build:
      context: './backrest/'
    hostname: backrest
    volumes:
      - ./:/data/
      - ./backup:/backup
      - ./volumes/backrest-config:/config
      - ./volumes/backrest-cache:/cache
      - ./volumes/backup:/backup_data/
      # to run in-app backup scripts
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - BACKREST_DATA=/backrest_data/ # path for backrest data. restic binary and the database are placed here.
      - BACKREST_CONFIG=/config/config.json # path for the backrest config file.
      - XDG_CACHE_HOME=/cache # path for the restic cache which greatly improves performance.
      - TZ=America/Los_Angeles # set the timezone for the container, used as the timezone for cron jobs.
    restart: unless-stopped
    ports:
      - 127.0.0.1:19898:9898
    networks:
      proxy:
        aliases: 
          - backrest.foswiki.docker.local

volumes:
  foswiki_www:
  solr_configsets:
  solr_foswiki:
  solr_logs:

networks:
  proxy:
    external: true
    name: "frontend-proxy"
  authentik:
    external: true
    name: "authentik"
  backend:
    internal: true
