version: '3'

services:

  foswiki:
    image: timlegge/docker-foswiki:latest
    restart: always
    depends_on: 
      - solr
    env_file:
      - ${PWD}/.env
    networks:
      - frontend
      - backend
    ports:
      - "$EXTERNAL_PORT:80"
    volumes:
      - solr_logs:/opt/solr/server/logs:z
      - solr_configsets:/opt/solr/server/solr/configsets:z
      - solr_foswiki:/opt/solr/server/solr/solr_foswiki:z
      - foswiki_www:/var/www/foswiki:z
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`${URL}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.entrypoints=websecure"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.tls.certresolver=${ACME}"

  solr:
    image: solr:5
    restart: always
    networks:
      - backend
    volumes:
      - solr_logs:/opt/solr/server/logs:z
      - solr_configsets:/opt/solr/server/solr/configsets:z
      - solr_foswiki:/opt/solr/server/solr/solr_foswiki:z
      - foswiki_www:/var/www/foswiki:z
    environment:
      - GC_LOG_OPTS=''
      - SOLR_LOG_LEVEL='WARN'

volumes:
  foswiki_www:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/volumes/foswiki_www/
      o: bind
  solr_configsets:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/volumes/solr_configsets
      o: bind
  solr_foswiki:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/volumes/solr_foswiki
      o: bind
  solr_logs:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/volumes/solr_logs
      o: bind

networks:
  frontend:
    external:
      name: traefik
  backend:
    internal: true
